import { createFileRoute } from "@tanstack/react-router";
import { Compass, Gauge, Layers, MessageCircle } from "lucide-react";

import { AppShell } from "@/components/app/AppShell";
import { Skeleton } from "@/components/ui/skeleton";
import { useAuth } from "@/hooks/useAuth";
import { useTeachingStrategy } from "@/hooks/useLesson";

export const Route = createFileRoute("/pedagogy")({
  component: PedagogyPage,
});

function PedagogyPage() {
  const { currentUser } = useAuth();
  const topic = currentUser?.learningTopic ?? "";
  const strategy = useTeachingStrategy({ learner_id: currentUser?.id ?? "", topic });

  return (
    <AppShell title="Teaching strategy" subtitle="Generated by the pedagogy agent from your saved learner profile." accent={strategy.isFetching ? "Reasoning" : "Agent generated"}>
      {strategy.isLoading && <Skeleton className="h-72 rounded-3xl" />}
      {strategy.isError && (
        <div className="rounded-3xl border border-rose/30 bg-rose/5 p-6">
          <div className="font-medium">Strategy generation failed</div>
          <p className="mt-2 text-sm text-muted-foreground">{strategy.error.message}</p>
          <button onClick={() => void strategy.refetch()} className="mt-4 rounded-full bg-foreground px-4 py-2 text-sm text-background">Retry generation</button>
        </div>
      )}
      {strategy.data && (
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          <Tile icon={Compass} label="Approach" value={strategy.data.strategy_type} />
          <Tile icon={Gauge} label="Pacing" value={strategy.data.pacing_strategy ?? "Not specified"} />
          <Tile icon={Layers} label="Difficulty" value={strategy.data.difficulty_level ?? "Not specified"} />
          <Tile icon={MessageCircle} label="Interaction density" value={strategy.data.interaction_density ?? "Not specified"} />
          <div className="rounded-3xl border border-border bg-card p-6 md:col-span-2 xl:col-span-4">
            <div className="text-[10px] uppercase tracking-[0.24em] text-muted-foreground">Recommended modalities</div>
            <div className="mt-4 flex flex-wrap gap-2">
              {strategy.data.recommended_modalities.map((modality) => (
                <span key={modality} className="rounded-full border border-border px-3 py-1.5 text-sm">{humanize(modality)}</span>
              ))}
            </div>
          </div>
        </div>
      )}
    </AppShell>
  );
}

function Tile({ icon: Icon, label, value }: { icon: React.ElementType; label: string; value: string }) {
  return (
    <div className="rounded-3xl border border-border bg-card p-5">
      <Icon className="size-4 text-plum" />
      <div className="mt-4 text-[10px] uppercase tracking-[0.2em] text-muted-foreground">{label}</div>
      <div className="mt-1 font-display text-2xl">{humanize(value)}</div>
    </div>
  );
}

function humanize(value: string) {
  return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}
