/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as PedagogyRouteImport } from './routes/pedagogy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LessonRouteImport } from './routes/lesson'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PedagogyRoute = PedagogyRouteImport.update({
  id: '/pedagogy',
  path: '/pedagogy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonRoute = LessonRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intelligence': typeof IntelligenceRoute
  '/knowledge': typeof KnowledgeRoute
  '/lesson': typeof LessonRoute
  '/login': typeof LoginRoute
  '/pedagogy': typeof PedagogyRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/progress': typeof ProgressRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intelligence': typeof IntelligenceRoute
  '/knowledge': typeof KnowledgeRoute
  '/lesson': typeof LessonRoute
  '/login': typeof LoginRoute
  '/pedagogy': typeof PedagogyRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/progress': typeof ProgressRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intelligence': typeof IntelligenceRoute
  '/knowledge': typeof KnowledgeRoute
  '/lesson': typeof LessonRoute
  '/login': typeof LoginRoute
  '/pedagogy': typeof PedagogyRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/progress': typeof ProgressRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/forgot-password'
    | '/intelligence'
    | '/knowledge'
    | '/lesson'
    | '/login'
    | '/pedagogy'
    | '/profile-setup'
    | '/progress'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/forgot-password'
    | '/intelligence'
    | '/knowledge'
    | '/lesson'
    | '/login'
    | '/pedagogy'
    | '/profile-setup'
    | '/progress'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/forgot-password'
    | '/intelligence'
    | '/knowledge'
    | '/lesson'
    | '/login'
    | '/pedagogy'
    | '/profile-setup'
    | '/progress'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IntelligenceRoute: typeof IntelligenceRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LessonRoute: typeof LessonRoute
  LoginRoute: typeof LoginRoute
  PedagogyRoute: typeof PedagogyRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  ProgressRoute: typeof ProgressRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedagogy': {
      id: '/pedagogy'
      path: '/pedagogy'
      fullPath: '/pedagogy'
      preLoaderRoute: typeof PedagogyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson': {
      id: '/lesson'
      path: '/lesson'
      fullPath: '/lesson'
      preLoaderRoute: typeof LessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IntelligenceRoute: IntelligenceRoute,
  KnowledgeRoute: KnowledgeRoute,
  LessonRoute: LessonRoute,
  LoginRoute: LoginRoute,
  PedagogyRoute: PedagogyRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  ProgressRoute: ProgressRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
