/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as PedagogyRouteImport } from './routes/pedagogy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LessonViewRouteImport } from './routes/lesson-view'
import { Route as LessonRouteImport } from './routes/lesson'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as JoinClassRouteImport } from './routes/join-class'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as CreateClassroomRouteImport } from './routes/create-classroom'
import { Route as ClassInsightsRouteImport } from './routes/class-insights'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinCodeRouteImport } from './routes/join.$code'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PedagogyRoute = PedagogyRouteImport.update({
  id: '/pedagogy',
  path: '/pedagogy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonViewRoute = LessonViewRouteImport.update({
  id: '/lesson-view',
  path: '/lesson-view',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonRoute = LessonRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinClassRoute = JoinClassRouteImport.update({
  id: '/join-class',
  path: '/join-class',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateClassroomRoute = CreateClassroomRouteImport.update({
  id: '/create-classroom',
  path: '/create-classroom',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassInsightsRoute = ClassInsightsRouteImport.update({
  id: '/class-insights',
  path: '/class-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assessment': typeof AssessmentRoute
  '/class-insights': typeof ClassInsightsRoute
  '/create-classroom': typeof CreateClassroomRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intelligence': typeof IntelligenceRoute
  '/join-class': typeof JoinClassRoute
  '/knowledge': typeof KnowledgeRoute
  '/lesson': typeof LessonRoute
  '/lesson-view': typeof LessonViewRoute
  '/login': typeof LoginRoute
  '/pedagogy': typeof PedagogyRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/progress': typeof ProgressRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/teacher': typeof TeacherRoute
  '/join/$code': typeof JoinCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assessment': typeof AssessmentRoute
  '/class-insights': typeof ClassInsightsRoute
  '/create-classroom': typeof CreateClassroomRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intelligence': typeof IntelligenceRoute
  '/join-class': typeof JoinClassRoute
  '/knowledge': typeof KnowledgeRoute
  '/lesson': typeof LessonRoute
  '/lesson-view': typeof LessonViewRoute
  '/login': typeof LoginRoute
  '/pedagogy': typeof PedagogyRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/progress': typeof ProgressRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/teacher': typeof TeacherRoute
  '/join/$code': typeof JoinCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assessment': typeof AssessmentRoute
  '/class-insights': typeof ClassInsightsRoute
  '/create-classroom': typeof CreateClassroomRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intelligence': typeof IntelligenceRoute
  '/join-class': typeof JoinClassRoute
  '/knowledge': typeof KnowledgeRoute
  '/lesson': typeof LessonRoute
  '/lesson-view': typeof LessonViewRoute
  '/login': typeof LoginRoute
  '/pedagogy': typeof PedagogyRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/progress': typeof ProgressRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/teacher': typeof TeacherRoute
  '/join/$code': typeof JoinCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/assessment'
    | '/class-insights'
    | '/create-classroom'
    | '/feedback'
    | '/forgot-password'
    | '/intelligence'
    | '/join-class'
    | '/knowledge'
    | '/lesson'
    | '/lesson-view'
    | '/login'
    | '/pedagogy'
    | '/profile-setup'
    | '/progress'
    | '/results'
    | '/signup'
    | '/teacher'
    | '/join/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/assessment'
    | '/class-insights'
    | '/create-classroom'
    | '/feedback'
    | '/forgot-password'
    | '/intelligence'
    | '/join-class'
    | '/knowledge'
    | '/lesson'
    | '/lesson-view'
    | '/login'
    | '/pedagogy'
    | '/profile-setup'
    | '/progress'
    | '/results'
    | '/signup'
    | '/teacher'
    | '/join/$code'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/assessment'
    | '/class-insights'
    | '/create-classroom'
    | '/feedback'
    | '/forgot-password'
    | '/intelligence'
    | '/join-class'
    | '/knowledge'
    | '/lesson'
    | '/lesson-view'
    | '/login'
    | '/pedagogy'
    | '/profile-setup'
    | '/progress'
    | '/results'
    | '/signup'
    | '/teacher'
    | '/join/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AssessmentRoute: typeof AssessmentRoute
  ClassInsightsRoute: typeof ClassInsightsRoute
  CreateClassroomRoute: typeof CreateClassroomRoute
  FeedbackRoute: typeof FeedbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IntelligenceRoute: typeof IntelligenceRoute
  JoinClassRoute: typeof JoinClassRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LessonRoute: typeof LessonRoute
  LessonViewRoute: typeof LessonViewRoute
  LoginRoute: typeof LoginRoute
  PedagogyRoute: typeof PedagogyRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  ProgressRoute: typeof ProgressRoute
  ResultsRoute: typeof ResultsRoute
  SignupRoute: typeof SignupRoute
  TeacherRoute: typeof TeacherRoute
  JoinCodeRoute: typeof JoinCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedagogy': {
      id: '/pedagogy'
      path: '/pedagogy'
      fullPath: '/pedagogy'
      preLoaderRoute: typeof PedagogyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-view': {
      id: '/lesson-view'
      path: '/lesson-view'
      fullPath: '/lesson-view'
      preLoaderRoute: typeof LessonViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson': {
      id: '/lesson'
      path: '/lesson'
      fullPath: '/lesson'
      preLoaderRoute: typeof LessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-class': {
      id: '/join-class'
      path: '/join-class'
      fullPath: '/join-class'
      preLoaderRoute: typeof JoinClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-classroom': {
      id: '/create-classroom'
      path: '/create-classroom'
      fullPath: '/create-classroom'
      preLoaderRoute: typeof CreateClassroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class-insights': {
      id: '/class-insights'
      path: '/class-insights'
      fullPath: '/class-insights'
      preLoaderRoute: typeof ClassInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AssessmentRoute: AssessmentRoute,
  ClassInsightsRoute: ClassInsightsRoute,
  CreateClassroomRoute: CreateClassroomRoute,
  FeedbackRoute: FeedbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IntelligenceRoute: IntelligenceRoute,
  JoinClassRoute: JoinClassRoute,
  KnowledgeRoute: KnowledgeRoute,
  LessonRoute: LessonRoute,
  LessonViewRoute: LessonViewRoute,
  LoginRoute: LoginRoute,
  PedagogyRoute: PedagogyRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  ProgressRoute: ProgressRoute,
  ResultsRoute: ResultsRoute,
  SignupRoute: SignupRoute,
  TeacherRoute: TeacherRoute,
  JoinCodeRoute: JoinCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
