export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  FORGOT_PASSWORD: "/forgot-password",
  PROFILE_SETUP: "/profile-setup",
  LESSON: "/lesson",
  ASSESSMENT: "/assessment",
  RESULTS: "/results",
  ALERTS: "/alerts",
  KNOWLEDGE: "/knowledge",
  PROGRESS: "/progress",
  INTELLIGENCE: "/intelligence",
  PEDAGOGY: "/pedagogy",
  FEEDBACK: "/feedback",
  TEACHER: "/teacher",
  CLASS_INSIGHTS: "/class-insights",
  CREATE_CLASSROOM: "/create-classroom",
  JOIN_CLASS: "/join-class",
} as const;
